apiVersion: skaffold/v4beta9
kind: Config
build:
  local:
    push: false
  # googleCloudBuild:
  #   projectId: microservices-class-udemy
  artifacts:
  #  - image: us.gcr.io/microservices-class-udemy/auth
    - image: beserkobob/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
manifests:
  rawYaml:
    - ./infra/k8s/*
deploy:
  kubectl: {}